Repository sendgrid/sendgrid-php, pull requests merged in 2018-10, with the labels that each got.

#698 Update prism version. Fixes #690
  test/prism.sh
Labels: difficulty: hard, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#743 Added Box attachment example (issue #481)
  USE_CASES.md
  composer.json
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#740 Fixes #739 Wrong condition
  lib/mail/EmailAddress.php
  test/unit/MailHelperTest.php
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: bug

#736 Update CONTRIBUTING - contribution guideline to branch off development
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#760 clean up shell script
  scripts/package.sh
  test/prism.sh
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement
