Repository sendgrid/sendgrid-php, pull requests merged in 2018-03, with the labels that each got.

#577 Update PHP Version terms
  .github/ISSUE_TEMPLATE
Labels: difficulty: easy, status: code review request, type: docs update

#576 Bad Request
  lib/helpers/mail/Mail.php
Labels: difficulty: easy, status: code review request, type: bug

#565 Add PHP 7.1 and 7.2 to Travis build matrix
  .travis.yml
Labels: difficulty: easy, status: code review request, type: community enhancement

#588 Fix broken unit tests
  test/unit/FilesExistTest.php
  test/unit/GenericTest.php
Labels: difficulty: easy, status: code review request, status: work in progress, type: sendgrid enhancement

#550 Added Code Review to Contributing.md
  CONTRIBUTING.md
  README.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: docs update

#575 Update README.md
  README.md
Labels: difficulty: easy, status: code review request, type: docs update

#545 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: bug, type: docs update

#526 Updated PHP VERSION.
  .github/ISSUE_TEMPLATE
Labels: difficulty: easy, hacktoberfest, status: code review request, type: sendgrid enhancement

#512 Omit PHP closing tag in use case sample
  USE_CASES.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: community enhancement

#502 added helper for new recipient form
  composer.json
  examples/helpers/contacts/recipients.php
  examples/helpers/mail/example.php
  lib/helpers/contacts/README.md
  lib/helpers/contacts/Recipients.php
  lib/loader.php
  test/unit/helpers/contacts/RecipientsTest.php
Labels: difficulty: hard, hacktoberfest, status: code review request, type: sendgrid enhancement

#506 Implemented stats helper
  composer.json
  examples/helpers/stats/example.php
  lib/helpers/stats/Stats.php
  test/unit/helpers/stats/StatsTest.php
Labels: difficulty: medium, hacktoberfest, status: code review request, type: community enhancement

#511 Add support for commas and semicolons in email name and add test
  lib/helpers/mail/Mail.php
  test/unit/Mail/MailHelperTest.php
Labels: difficulty: medium, hacktoberfest, status: code review request, type: sendgrid enhancement

#493 Set attachment content from path
  USE_CASES.md
  lib/helpers/mail/Mail.php
  test/data/test.txt
  test/unit/Mail/MailHelperTest.php
Labels: difficulty: medium, hacktoberfest, status: waiting for feedback, type: sendgrid enhancement
