Repository sendgrid/sendgrid-php, pull requests merged in 2018-08, with the labels that each got.

#618 Attachments now automatically get base64 encoded if they are not already
  lib/mail/Attachment.php
  test/unit/Attachments.php
  test/unit/KitchenSinkTest.php
Labels: difficulty: medium, status: code review request, type: community enhancement

#625 Fix setGroupsToDisplay's handling of array arguments
  lib/mail/GroupsToDisplay.php
  test/unit/KitchenSinkTest.php
Labels: status: code review request, type: bug

#628 Potential fix for: Remove unnecessary linter warning from phpcs
  phpcs.xml
Labels: difficulty: easy, status: code review request, type: community enhancement

#620 PHPDoc & code improvements
  lib/mail/Mail.php
Labels: difficulty: easy, status: code review request, type: community enhancement

#660 Remaining cleanup items from PR #620
  lib/mail/EmailAddress.php
  lib/mail/Mail.php
Labels: difficulty: medium, status: code review request, status: ready for deploy, type: sendgrid enhancement

#633 The following changes relate to use in a non-composer environment:
  README.md
  USAGE.md
  USE_CASES.md
  lib/loader.php
Labels: status: code review request, type: bug

#651 Add try / catch to examples. Fixes #617
  examples/accesssettings/accesssettings.php
  examples/alerts/alerts.php
  examples/apikeys/apikeys.php
  examples/asm/asm.php
  examples/browsers/browsers.php
  examples/campaigns/campaigns.php
  examples/categories/categories.php
  examples/clients/clients.php
  examples/contactdb/contactdb.php
  examples/devices/devices.php
  examples/geo/geo.php
  examples/helpers/contacts/recipients.php
  examples/helpers/mail/example.php
  examples/ips/ips.php
  examples/mail/mail.php
  examples/mailboxproviders/mailboxproviders.php
  examples/mailsettings/mailsettings.php
  examples/partnersettings/partnersettings.php
  examples/scopes/scopes.php
  examples/senders/senders.php
  examples/stats/stats.php
  examples/subusers/subusers.php
  examples/suppression/suppression.php
  examples/templates/templates.php
  examples/trackingsettings/trackingsettings.php
  examples/user/user.php
  examples/whitelabel/whitelabel.php
Labels: status: code review request

#661 updated Readme tag
  README.md
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#662 Fix for #629
  lib/mail/Mail.php
Labels: difficulty: easy, status: ready for deploy, type: bug

#571 Add ability to impersonate subuser
  lib/SendGrid.php
  test/unit/SendGridTest.php
Labels: difficulty: medium, status: code review request, type: sendgrid enhancement

#652 Fixes #612 Add TypeException and include type validations in classes inside mail/
  examples/helpers/mail/example.php
  lib/mail/Asm.php
  lib/mail/Attachment.php
  lib/mail/BatchId.php
  lib/mail/BccSettings.php
  lib/mail/BypassListManagement.php
  lib/mail/Category.php
  lib/mail/ClickTracking.php
  lib/mail/Content.php
  lib/mail/CustomArg.php
  lib/mail/EmailAddress.php
  lib/mail/Footer.php
  lib/mail/Ganalytics.php
  lib/mail/GroupId.php
  lib/mail/GroupsToDisplay.php
  lib/mail/Header.php
  lib/mail/IpPoolName.php
  lib/mail/Mail.php
  lib/mail/MailSettings.php
  lib/mail/OpenTracking.php
  lib/mail/Personalization.php
  lib/mail/SandBoxMode.php
  lib/mail/Section.php
  lib/mail/SendAt.php
  lib/mail/SpamCheck.php
  lib/mail/Subject.php
  lib/mail/SubscriptionTracking.php
  lib/mail/Substitution.php
  lib/mail/TemplateId.php
  lib/mail/TrackingSettings.php
  lib/mail/TypeException.php
  test/unit/MailHelperTest.php
  test/unit/MultipleEmailToMultipleRecipientsTest.php
Labels: difficulty: medium, status: code review request, type: community enhancement

#668 isBase64 function fix
  CHANGELOG.md
  lib/mail/Attachment.php
Labels: difficulty: easy, status: code review request, status: ready for deploy, type: bug
