Repository sendgrid/sendgrid-php, pull requests merged in 2018-11, with the labels that each got.

#773 Added Announcement
  README.md
Labels: difficulty: easy, status: code review request

#764 fix #763
  README.md
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#769 Updations in prerequisites #768
  README.md
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#783 Remove references to 'whitelabel'
  USAGE.md
  USE_CASES.md
  examples/senderauthentication/senderauthentication.php
  test/integration/SenderAuthentication/DomainAuthenticationTest.php
  test/integration/SenderAuthentication/LinkBrandingTest.php
  test/integration/SenderAuthentication/ReverseDNSTest.php
Labels: difficulty: easy, status: code review request, type: docs update
