Repository sendgrid/sendgrid-php, pull requests merged in 2019-05, with the labels that each got.

#841 Make $emailAddress on TypeException to be evaluated
  lib/mail/EmailAddress.php
Labels: difficulty: easy, status: ready for deploy, type: community enhancement

#705 Fixing issue #686
  lib/mail/Mail.php
  test/unit/MailHelperTest.php
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: bug

#837 Fixes #788 - Add missing parameter for addCc and addBcc methods
  lib/mail/Mail.php
Labels: difficulty: easy, status: code review request, status: ready for deploy

#836 Update example.php. Add personalization example as per #792
  examples/helpers/mail/example.php
Labels: difficulty: medium, status: code review request, status: ready for deploy, type: docs update
