Repository sendgrid/sendgrid-php, pull requests merged in 2020-08, with the labels that each got.

#984 docs: Reduce excessive comments in code examples
  README.md
  USAGE.md
  USE_CASES.md
  examples/accesssettings/accesssettings.php
  examples/alerts/alerts.php
  examples/apikeys/apikeys.php
  examples/asm/asm.php
  examples/browsers/browsers.php
  examples/campaigns/campaigns.php
  examples/categories/categories.php
  examples/clients/clients.php
  examples/contactdb/contactdb.php
  examples/devices/devices.php
  examples/geo/geo.php
  examples/helpers/contacts/recipients.php
  examples/helpers/mail/example.php
  examples/helpers/stats/example.php
  examples/ips/ips.php
  examples/mail/mail.php
  examples/mailboxproviders/mailboxproviders.php
  examples/mailsettings/mailsettings.php
  examples/partnersettings/partnersettings.php
  examples/scopes/scopes.php
  examples/senderauthentication/senderauthentication.php
  examples/senders/senders.php
  examples/stats/stats.php
  examples/subusers/subusers.php
  examples/suppression/suppression.php
  examples/templates/templates.php
  examples/trackingsettings/trackingsettings.php
  examples/user/user.php
Labels: status: waiting for feedback

#756 test: Add more scenarios for email address encoding
  test/unit/EmailAddressTest.php
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#993 chore: update GitHub branch references to use HEAD
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  USAGE.md
  USE_CASES.md
  examples/mail/mail.php
  lib/contacts/README.md
  lib/mail/README.md
  twilio_sendgrid_logo.png
Labels: status: code review request

#729 docs: Added S3 attachment example
  USE_CASES.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#735 test: add unit tests for lib/email
  lib/mail/SubscriptionTracking.php
  test/unit/AsmTest.php
  test/unit/AttachmentsTest.php
  test/unit/BatchIdTest.php
  test/unit/BccSettingsTest.php
  test/unit/BypassListManagementTest.php
  test/unit/CategoryTest.php
  test/unit/ClickTrackingTest.php
  test/unit/ContentTest.php
  test/unit/CustomArgTest.php
  test/unit/DynamicTemplateTest.php
  test/unit/EmailAddressTest.php
  test/unit/FilesExistTest.php
  test/unit/FooterTest.php
  test/unit/GanalyticsTest.php
  test/unit/GroupIdTest.php
  test/unit/GroupsToDisplayTest.php
  test/unit/HeaderTest.php
  test/unit/HtmlContentTest.php
  test/unit/IpPoolNameTest.php
  test/unit/KitchenSinkTest.php
  test/unit/MailGetContentsTest.php
  test/unit/MailTest.php
  test/unit/MultipleEmailToMultipleRecipientsTest.php
  test/unit/OpenTrackingTest.php
  test/unit/PersonalizationTest.php
  test/unit/PlainTextContentTest.php
  test/unit/SandBoxModeTest.php
  test/unit/SectionTest.php
  test/unit/SendAtTest.php
  test/unit/SingleEmailToASingleRecipientTest.php
  test/unit/SingleEmailToMultipleRecipientsTest.php
  test/unit/SpamCheckTest.php
  test/unit/SubjectTest.php
  test/unit/SubscriptionTrackingTest.php
  test/unit/SubstitutionTest.php
  test/unit/TemplateIdTest.php
  test/unit/TrackingSettingsTest.php
  test/unit/TwilioEmailTest.php
Labels: difficulty: medium, good first issue, hacktoberfest, status: code review request, status: hacktoberfest approved

#717 docs: Update documentation for retrieving a list of all templates
  USAGE.md
  examples/templates/templates.php
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#1001 fix: support 'to' addresses with subjects
  lib/mail/EmailAddress.php
  lib/mail/Mail.php
  lib/stats/Stats.php
  test/unit/MultipleEmailToMultipleRecipientsTest.php
Labels: status: code review request
