Repository sendgrid/sendgrid-php, pull requests merged in 2020-07, with the labels that each got.

#985 feat: Additional check for existence of Composer autoloader
  CONTRIBUTING.md
  sendgrid-php.php
Labels: status: code review request

#762 feat: enhanced type exception handling
  composer.json
  lib/eventwebhook/EventWebhookHeader.php
  lib/helper/Assert.php
  lib/loader.php
  lib/mail/Asm.php
  lib/mail/Attachment.php
  lib/mail/BatchId.php
  lib/mail/BccSettings.php
  lib/mail/BypassListManagement.php
  lib/mail/Category.php
  lib/mail/ClickTracking.php
  lib/mail/Content.php
  lib/mail/CustomArg.php
  lib/mail/EmailAddress.php
  lib/mail/Footer.php
  lib/mail/Ganalytics.php
  lib/mail/GroupId.php
  lib/mail/GroupsToDisplay.php
  lib/mail/Header.php
  lib/mail/HtmlContent.php
  lib/mail/IpPoolName.php
  lib/mail/Mail.php
  lib/mail/MailSettings.php
  lib/mail/MimeType.php
  lib/mail/OpenTracking.php
  lib/mail/Personalization.php
  lib/mail/PlainTextContent.php
  lib/mail/SandBoxMode.php
  lib/mail/Section.php
  lib/mail/SendAt.php
  lib/mail/SpamCheck.php
  lib/mail/Subject.php
  lib/mail/SubscriptionTracking.php
  lib/mail/Substitution.php
  lib/mail/TemplateId.php
  lib/mail/TrackingSettings.php
  lib/mail/TypeException.php
  test/BaseTestClass.php
  test/phpunit.xml.dist
  test/unit/AssertTest.php
  test/unit/AttachmentsTest.php
  test/unit/EmailAddressTest.php
  test/unit/GroupsToDisplayTest.php
  test/unit/MailGetContentsTest.php
  test/unit/MultipleEmailToMultipleRecipientsTest.php
Labels: difficulty: hard, hacktoberfest, status: code review request, status: hacktoberfest approved, type: sendgrid enhancement

#759 docs: add Email Activity API to usage docs
  USAGE.md
  USE_CASES.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#778 docs: fix grammar issue in CHANGELOG
  CHANGELOG.md
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#990 chore: migrate to new default sendgrid-oai branch
  Makefile
Labels: status: code review request

#755 fix: remove loader.php and update CONTRIBUTING.md
  CONTRIBUTING.md
  lib/loader.php
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved
