Repository sendgrid/sendgrid-php, pull requests merged in 2020-01, with the labels that each got.

#887 fix: correct the mail helper readme link in example
  examples/mail/mail.php
Labels: status: code review request

#770 fix: update the link for cURL example in Troubleshooting.MD
  TROUBLESHOOTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#761 fix: correct the License file path in ReadMe
  README.md
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#757 fix: remove dead code when setting the subject
  lib/mail/EmailAddress.php
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#765 fix: correct typo in PR template from "Sendgrid" to "SendGrid"
  .github/PULL_REQUEST_TEMPLATE
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#742 docs: properly capitalize brands GitHub and SendGrid
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
  lib/contacts/README.md
  test/unit/AttachmentsTest.php
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved

#926 chore: prep the repo for automated releasing
  .gitignore
  .travis.yml
  LICENSE.md
  Makefile
  README.md
  composer.json
  test/unit/SendGridTest.php
Labels: status: code review request

#710 docs: correct the *.md files using Grammarly
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  USAGE.md
  USE_CASES.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#928 docs: baseline all the templated markdown docs
  .github/ISSUE_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  test/unit/FilesExistTest.php
Labels: status: code review request
