Repository sendgrid/sendgrid-php, pull requests merged in 2020-10, with the labels that each got.

#1009 docs: Incorrect value order in example array for addAttachments
  USE_CASES.md
Labels: status: ready for deploy, type: docs update

#704 test: Adding php static analysis
  Makefile
Labels: difficulty: medium, status: code review request

#674 feat: Allows for a user to utilize self-signed certificates
  lib/BaseSendGridClientInterface.php
  lib/SendGrid.php
  lib/TwilioEmail.php
Labels: difficulty: easy, status: code review request
